//Project Euler 2

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

int sum = 0;
int fibMax = 4000000;
int num1 = 1;
int num2 = 2;
int num3;

if (num1 % 2 == 0 && num1 > 2)
{
    sum = sum + num1;
}
if (num2 % 2 == 0 && num2 >= 2)
{
    sum = sum + num2;
}

while (num1 < fibMax && num2 < fibMax)
{
    num3 = num1 + num2;
    if (num3 % 2 == 0)
    {
        sum = sum + num3;
    }

    if (num1 < num2)
    {
        num1 = num3;
    }
    else
    {
        num2 = num3;
    }
}

Console.WriteLine("Sum of even numbers: " + sum);